[build]
command = "yarn rw deploy netlify"
publish = "web/dist"
functions = "api/dist/functions"

[dev]
  # To use [Netlify Dev](https://www.netlify.com/products/dev/),
  # install netlify-cli from https://docs.netlify.com/cli/get-started/#installation
  # and then use netlify link https://docs.netlify.com/cli/get-started/#link-and-unlink-sites
  # to connect your local project to a site already on Netlify
  # then run netlify dev and our app will be accessible on the port specified below
  framework = "redwoodjs"
  # Set targetPort to the [web] side port as defined in redwood.toml
  targetPort = 8910
  # Point your browser to this port to access your RedwoodJS app
  port = 8888

[context.netlify-apollo.environment]
  DATADOG_SOURCE = "netlify"
  DATADOG_TAGS = "apollo"
  DATADOG_SERVICE = "netlify-apollo"

[context.netlify-envelop.environment]
  DATADOG_SOURCE = "netlify"
  DATADOG_TAGS = "envelop"
  DATADOG_SERVICE = "netlify-envelop"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
